baseURL = "https://book-review.biz/"
languageCode = "en-us"
title = "Book Review BIZ"
theme = "Mainroad"

[pagination]
pagerSize = 10

[taxonomies]
category = "categories"
tag      = "tags"

buildFuture = true